/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluxpay

import (
	"encoding/json"
)

// ModelsWechatOrderDetail struct for ModelsWechatOrderDetail
type ModelsWechatOrderDetail struct {
	Amount *int32 `json:"amount,omitempty"`
	Appid *string `json:"appid,omitempty"`
	Attach *string `json:"attach,omitempty"`
	BankType *string `json:"bank_type,omitempty"`
	Mchid *string `json:"mchid,omitempty"`
	Payer *string `json:"payer,omitempty"`
	SuccessTime *string `json:"success_time,omitempty"`
	TradeNo *string `json:"trade_no,omitempty"`
	TradeState *string `json:"trade_state,omitempty"`
	TradeStateDesc *string `json:"trade_state_desc,omitempty"`
	TradeType *string `json:"trade_type,omitempty"`
	TransactionId *string `json:"transaction_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelsWechatOrderDetail ModelsWechatOrderDetail

// NewModelsWechatOrderDetail instantiates a new ModelsWechatOrderDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsWechatOrderDetail() *ModelsWechatOrderDetail {
	this := ModelsWechatOrderDetail{}
	return &this
}

// NewModelsWechatOrderDetailWithDefaults instantiates a new ModelsWechatOrderDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsWechatOrderDetailWithDefaults() *ModelsWechatOrderDetail {
	this := ModelsWechatOrderDetail{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetAmount() int32 {
	if o == nil || o.Amount == nil {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetAmountOk() (*int32, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ModelsWechatOrderDetail) SetAmount(v int32) {
	o.Amount = &v
}

// GetAppid returns the Appid field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetAppid() string {
	if o == nil || o.Appid == nil {
		var ret string
		return ret
	}
	return *o.Appid
}

// GetAppidOk returns a tuple with the Appid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetAppidOk() (*string, bool) {
	if o == nil || o.Appid == nil {
		return nil, false
	}
	return o.Appid, true
}

// HasAppid returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasAppid() bool {
	if o != nil && o.Appid != nil {
		return true
	}

	return false
}

// SetAppid gets a reference to the given string and assigns it to the Appid field.
func (o *ModelsWechatOrderDetail) SetAppid(v string) {
	o.Appid = &v
}

// GetAttach returns the Attach field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetAttach() string {
	if o == nil || o.Attach == nil {
		var ret string
		return ret
	}
	return *o.Attach
}

// GetAttachOk returns a tuple with the Attach field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetAttachOk() (*string, bool) {
	if o == nil || o.Attach == nil {
		return nil, false
	}
	return o.Attach, true
}

// HasAttach returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasAttach() bool {
	if o != nil && o.Attach != nil {
		return true
	}

	return false
}

// SetAttach gets a reference to the given string and assigns it to the Attach field.
func (o *ModelsWechatOrderDetail) SetAttach(v string) {
	o.Attach = &v
}

// GetBankType returns the BankType field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetBankType() string {
	if o == nil || o.BankType == nil {
		var ret string
		return ret
	}
	return *o.BankType
}

// GetBankTypeOk returns a tuple with the BankType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetBankTypeOk() (*string, bool) {
	if o == nil || o.BankType == nil {
		return nil, false
	}
	return o.BankType, true
}

// HasBankType returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasBankType() bool {
	if o != nil && o.BankType != nil {
		return true
	}

	return false
}

// SetBankType gets a reference to the given string and assigns it to the BankType field.
func (o *ModelsWechatOrderDetail) SetBankType(v string) {
	o.BankType = &v
}

// GetMchid returns the Mchid field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetMchid() string {
	if o == nil || o.Mchid == nil {
		var ret string
		return ret
	}
	return *o.Mchid
}

// GetMchidOk returns a tuple with the Mchid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetMchidOk() (*string, bool) {
	if o == nil || o.Mchid == nil {
		return nil, false
	}
	return o.Mchid, true
}

// HasMchid returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasMchid() bool {
	if o != nil && o.Mchid != nil {
		return true
	}

	return false
}

// SetMchid gets a reference to the given string and assigns it to the Mchid field.
func (o *ModelsWechatOrderDetail) SetMchid(v string) {
	o.Mchid = &v
}

// GetPayer returns the Payer field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetPayer() string {
	if o == nil || o.Payer == nil {
		var ret string
		return ret
	}
	return *o.Payer
}

// GetPayerOk returns a tuple with the Payer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetPayerOk() (*string, bool) {
	if o == nil || o.Payer == nil {
		return nil, false
	}
	return o.Payer, true
}

// HasPayer returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasPayer() bool {
	if o != nil && o.Payer != nil {
		return true
	}

	return false
}

// SetPayer gets a reference to the given string and assigns it to the Payer field.
func (o *ModelsWechatOrderDetail) SetPayer(v string) {
	o.Payer = &v
}

// GetSuccessTime returns the SuccessTime field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetSuccessTime() string {
	if o == nil || o.SuccessTime == nil {
		var ret string
		return ret
	}
	return *o.SuccessTime
}

// GetSuccessTimeOk returns a tuple with the SuccessTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetSuccessTimeOk() (*string, bool) {
	if o == nil || o.SuccessTime == nil {
		return nil, false
	}
	return o.SuccessTime, true
}

// HasSuccessTime returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasSuccessTime() bool {
	if o != nil && o.SuccessTime != nil {
		return true
	}

	return false
}

// SetSuccessTime gets a reference to the given string and assigns it to the SuccessTime field.
func (o *ModelsWechatOrderDetail) SetSuccessTime(v string) {
	o.SuccessTime = &v
}

// GetTradeNo returns the TradeNo field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetTradeNo() string {
	if o == nil || o.TradeNo == nil {
		var ret string
		return ret
	}
	return *o.TradeNo
}

// GetTradeNoOk returns a tuple with the TradeNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetTradeNoOk() (*string, bool) {
	if o == nil || o.TradeNo == nil {
		return nil, false
	}
	return o.TradeNo, true
}

// HasTradeNo returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasTradeNo() bool {
	if o != nil && o.TradeNo != nil {
		return true
	}

	return false
}

// SetTradeNo gets a reference to the given string and assigns it to the TradeNo field.
func (o *ModelsWechatOrderDetail) SetTradeNo(v string) {
	o.TradeNo = &v
}

// GetTradeState returns the TradeState field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetTradeState() string {
	if o == nil || o.TradeState == nil {
		var ret string
		return ret
	}
	return *o.TradeState
}

// GetTradeStateOk returns a tuple with the TradeState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetTradeStateOk() (*string, bool) {
	if o == nil || o.TradeState == nil {
		return nil, false
	}
	return o.TradeState, true
}

// HasTradeState returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasTradeState() bool {
	if o != nil && o.TradeState != nil {
		return true
	}

	return false
}

// SetTradeState gets a reference to the given string and assigns it to the TradeState field.
func (o *ModelsWechatOrderDetail) SetTradeState(v string) {
	o.TradeState = &v
}

// GetTradeStateDesc returns the TradeStateDesc field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetTradeStateDesc() string {
	if o == nil || o.TradeStateDesc == nil {
		var ret string
		return ret
	}
	return *o.TradeStateDesc
}

// GetTradeStateDescOk returns a tuple with the TradeStateDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetTradeStateDescOk() (*string, bool) {
	if o == nil || o.TradeStateDesc == nil {
		return nil, false
	}
	return o.TradeStateDesc, true
}

// HasTradeStateDesc returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasTradeStateDesc() bool {
	if o != nil && o.TradeStateDesc != nil {
		return true
	}

	return false
}

// SetTradeStateDesc gets a reference to the given string and assigns it to the TradeStateDesc field.
func (o *ModelsWechatOrderDetail) SetTradeStateDesc(v string) {
	o.TradeStateDesc = &v
}

// GetTradeType returns the TradeType field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetTradeType() string {
	if o == nil || o.TradeType == nil {
		var ret string
		return ret
	}
	return *o.TradeType
}

// GetTradeTypeOk returns a tuple with the TradeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetTradeTypeOk() (*string, bool) {
	if o == nil || o.TradeType == nil {
		return nil, false
	}
	return o.TradeType, true
}

// HasTradeType returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasTradeType() bool {
	if o != nil && o.TradeType != nil {
		return true
	}

	return false
}

// SetTradeType gets a reference to the given string and assigns it to the TradeType field.
func (o *ModelsWechatOrderDetail) SetTradeType(v string) {
	o.TradeType = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *ModelsWechatOrderDetail) GetTransactionId() string {
	if o == nil || o.TransactionId == nil {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatOrderDetail) GetTransactionIdOk() (*string, bool) {
	if o == nil || o.TransactionId == nil {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *ModelsWechatOrderDetail) HasTransactionId() bool {
	if o != nil && o.TransactionId != nil {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *ModelsWechatOrderDetail) SetTransactionId(v string) {
	o.TransactionId = &v
}

func (o ModelsWechatOrderDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Appid != nil {
		toSerialize["appid"] = o.Appid
	}
	if o.Attach != nil {
		toSerialize["attach"] = o.Attach
	}
	if o.BankType != nil {
		toSerialize["bank_type"] = o.BankType
	}
	if o.Mchid != nil {
		toSerialize["mchid"] = o.Mchid
	}
	if o.Payer != nil {
		toSerialize["payer"] = o.Payer
	}
	if o.SuccessTime != nil {
		toSerialize["success_time"] = o.SuccessTime
	}
	if o.TradeNo != nil {
		toSerialize["trade_no"] = o.TradeNo
	}
	if o.TradeState != nil {
		toSerialize["trade_state"] = o.TradeState
	}
	if o.TradeStateDesc != nil {
		toSerialize["trade_state_desc"] = o.TradeStateDesc
	}
	if o.TradeType != nil {
		toSerialize["trade_type"] = o.TradeType
	}
	if o.TransactionId != nil {
		toSerialize["transaction_id"] = o.TransactionId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ModelsWechatOrderDetail) UnmarshalJSON(bytes []byte) (err error) {
	varModelsWechatOrderDetail := _ModelsWechatOrderDetail{}

	if err = json.Unmarshal(bytes, &varModelsWechatOrderDetail); err == nil {
		*o = ModelsWechatOrderDetail(varModelsWechatOrderDetail)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "appid")
		delete(additionalProperties, "attach")
		delete(additionalProperties, "bank_type")
		delete(additionalProperties, "mchid")
		delete(additionalProperties, "payer")
		delete(additionalProperties, "success_time")
		delete(additionalProperties, "trade_no")
		delete(additionalProperties, "trade_state")
		delete(additionalProperties, "trade_state_desc")
		delete(additionalProperties, "trade_type")
		delete(additionalProperties, "transaction_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelsWechatOrderDetail struct {
	value *ModelsWechatOrderDetail
	isSet bool
}

func (v NullableModelsWechatOrderDetail) Get() *ModelsWechatOrderDetail {
	return v.value
}

func (v *NullableModelsWechatOrderDetail) Set(val *ModelsWechatOrderDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsWechatOrderDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsWechatOrderDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsWechatOrderDetail(val *ModelsWechatOrderDetail) *NullableModelsWechatOrderDetail {
	return &NullableModelsWechatOrderDetail{value: val, isSet: true}
}

func (v NullableModelsWechatOrderDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsWechatOrderDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


