/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluxpay

import (
	"encoding/json"
)

// ModelsWechatRefundDetail struct for ModelsWechatRefundDetail
type ModelsWechatRefundDetail struct {
	// 金额详细信息
	Amount *int32 `json:"amount,omitempty"`
	// 枚举值： - ORIGINAL—原路退款 - BALANCE—退回到余额 - OTHER_BALANCE—原账户异常退到其他余额账户 - OTHER_BANKCARD—原银行卡异常退到其他银行卡 * `ORIGINAL` - 原路退款 * `BALANCE` - 退回到余额 * `OTHER_BALANCE` - 原账户异常退到其他余额账户 * `OTHER_BANKCARD` - 原银行卡异常退到其他银行卡
	Channel *string `json:"channel,omitempty"`
	// 退款受理时间，遵循rfc3339标准格式，格式为YYYY-MM-DDTHH:mm:ss+TIMEZONE，YYYY-MM-DD表示年月日，T出现在字符串中，表示time元素的开头，HH:mm:ss表示时分秒，TIMEZONE表示时区（+08:00表示东八区时间，领先UTC 8小时，即北京时间）。例如：2015-05-20T13:29:35+08:00表示，北京时间2015年5月20日13点29分35秒。
	CreateTime *string `json:"create_time,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	DeletedAt *GormDeletedAt `json:"deleted_at,omitempty"`
	// 退款所使用资金对应的资金账户类型 枚举值： - UNSETTLED : 未结算资金 - AVAILABLE : 可用余额 - UNAVAILABLE : 不可用余额 - OPERATION : 运营户 - BASIC : 基本账户（含可用余额和不可用余额） * `UNSETTLED` - 未结算资金 * `AVAILABLE` - 可用余额 * `UNAVAILABLE` - 不可用余额 * `OPERATION` - 运营户 * `BASIC` - 基本账户（含可用余额和不可用余额）
	FundsAccount *string `json:"funds_account,omitempty"`
	Id *int32 `json:"id,omitempty"`
	// 商户系统内部的退款单号，商户系统内部唯一，只能是数字、大小写字母_-|*@ ，同一退款单号多次请求只退一笔。
	OutRefundNo *string `json:"out_refund_no,omitempty"`
	// 原支付交易对应的商户订单号
	OutTradeNo *string `json:"out_trade_no,omitempty"`
	RefundId *string `json:"refund_id,omitempty"`
	// 退款到银行发现用户的卡作废或者冻结了，导致原路退款银行卡失败，可前往商户平台（pay.weixin.qq.com）-交易中心，手动处理此笔退款。 枚举值： - SUCCESS—退款成功 - CLOSED—退款关闭 - PROCESSING—退款处理中 - ABNORMAL—退款异常 * `SUCCESS` - 退款成功 * `CLOSED` - 退款关闭 * `PROCESSING` - 退款处理中 * `ABNORMAL` - 退款异常
	Status *string `json:"status,omitempty"`
	// 退款成功时间，退款状态status为SUCCESS（退款成功）时，返回该字段。遵循rfc3339标准格式，格式为YYYY-MM-DDTHH:mm:ss+TIMEZONE，YYYY-MM-DD表示年月日，T出现在字符串中，表示time元素的开头，HH:mm:ss表示时分秒，TIMEZONE表示时区（+08:00表示东八区时间，领先UTC 8小时，即北京时间）。例如：2015-05-20T13:29:35+08:00表示，北京时间2015年5月20日13点29分35秒。
	SuccessTime *string `json:"success_time,omitempty"`
	// 微信支付交易订单号
	TransactionId *string `json:"transaction_id,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	// 取当前退款单的退款入账方，有以下几种情况： 1）退回银行卡：{银行名称}{卡类型}{卡尾号} 2）退回支付用户零钱:支付用户零钱 3）退还商户:商户基本账户商户结算银行账户 4）退回支付用户零钱通:支付用户零钱通
	UserReceivedAccount *string `json:"user_received_account,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelsWechatRefundDetail ModelsWechatRefundDetail

// NewModelsWechatRefundDetail instantiates a new ModelsWechatRefundDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsWechatRefundDetail() *ModelsWechatRefundDetail {
	this := ModelsWechatRefundDetail{}
	return &this
}

// NewModelsWechatRefundDetailWithDefaults instantiates a new ModelsWechatRefundDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsWechatRefundDetailWithDefaults() *ModelsWechatRefundDetail {
	this := ModelsWechatRefundDetail{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetAmount() int32 {
	if o == nil || o.Amount == nil {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetAmountOk() (*int32, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ModelsWechatRefundDetail) SetAmount(v int32) {
	o.Amount = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetChannel() string {
	if o == nil || o.Channel == nil {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetChannelOk() (*string, bool) {
	if o == nil || o.Channel == nil {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasChannel() bool {
	if o != nil && o.Channel != nil {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *ModelsWechatRefundDetail) SetChannel(v string) {
	o.Channel = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetCreateTime() string {
	if o == nil || o.CreateTime == nil {
		var ret string
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetCreateTimeOk() (*string, bool) {
	if o == nil || o.CreateTime == nil {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasCreateTime() bool {
	if o != nil && o.CreateTime != nil {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given string and assigns it to the CreateTime field.
func (o *ModelsWechatRefundDetail) SetCreateTime(v string) {
	o.CreateTime = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelsWechatRefundDetail) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetDeletedAt() GormDeletedAt {
	if o == nil || o.DeletedAt == nil {
		var ret GormDeletedAt
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetDeletedAtOk() (*GormDeletedAt, bool) {
	if o == nil || o.DeletedAt == nil {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasDeletedAt() bool {
	if o != nil && o.DeletedAt != nil {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given GormDeletedAt and assigns it to the DeletedAt field.
func (o *ModelsWechatRefundDetail) SetDeletedAt(v GormDeletedAt) {
	o.DeletedAt = &v
}

// GetFundsAccount returns the FundsAccount field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetFundsAccount() string {
	if o == nil || o.FundsAccount == nil {
		var ret string
		return ret
	}
	return *o.FundsAccount
}

// GetFundsAccountOk returns a tuple with the FundsAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetFundsAccountOk() (*string, bool) {
	if o == nil || o.FundsAccount == nil {
		return nil, false
	}
	return o.FundsAccount, true
}

// HasFundsAccount returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasFundsAccount() bool {
	if o != nil && o.FundsAccount != nil {
		return true
	}

	return false
}

// SetFundsAccount gets a reference to the given string and assigns it to the FundsAccount field.
func (o *ModelsWechatRefundDetail) SetFundsAccount(v string) {
	o.FundsAccount = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ModelsWechatRefundDetail) SetId(v int32) {
	o.Id = &v
}

// GetOutRefundNo returns the OutRefundNo field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetOutRefundNo() string {
	if o == nil || o.OutRefundNo == nil {
		var ret string
		return ret
	}
	return *o.OutRefundNo
}

// GetOutRefundNoOk returns a tuple with the OutRefundNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetOutRefundNoOk() (*string, bool) {
	if o == nil || o.OutRefundNo == nil {
		return nil, false
	}
	return o.OutRefundNo, true
}

// HasOutRefundNo returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasOutRefundNo() bool {
	if o != nil && o.OutRefundNo != nil {
		return true
	}

	return false
}

// SetOutRefundNo gets a reference to the given string and assigns it to the OutRefundNo field.
func (o *ModelsWechatRefundDetail) SetOutRefundNo(v string) {
	o.OutRefundNo = &v
}

// GetOutTradeNo returns the OutTradeNo field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetOutTradeNo() string {
	if o == nil || o.OutTradeNo == nil {
		var ret string
		return ret
	}
	return *o.OutTradeNo
}

// GetOutTradeNoOk returns a tuple with the OutTradeNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetOutTradeNoOk() (*string, bool) {
	if o == nil || o.OutTradeNo == nil {
		return nil, false
	}
	return o.OutTradeNo, true
}

// HasOutTradeNo returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasOutTradeNo() bool {
	if o != nil && o.OutTradeNo != nil {
		return true
	}

	return false
}

// SetOutTradeNo gets a reference to the given string and assigns it to the OutTradeNo field.
func (o *ModelsWechatRefundDetail) SetOutTradeNo(v string) {
	o.OutTradeNo = &v
}

// GetRefundId returns the RefundId field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetRefundId() string {
	if o == nil || o.RefundId == nil {
		var ret string
		return ret
	}
	return *o.RefundId
}

// GetRefundIdOk returns a tuple with the RefundId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetRefundIdOk() (*string, bool) {
	if o == nil || o.RefundId == nil {
		return nil, false
	}
	return o.RefundId, true
}

// HasRefundId returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasRefundId() bool {
	if o != nil && o.RefundId != nil {
		return true
	}

	return false
}

// SetRefundId gets a reference to the given string and assigns it to the RefundId field.
func (o *ModelsWechatRefundDetail) SetRefundId(v string) {
	o.RefundId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ModelsWechatRefundDetail) SetStatus(v string) {
	o.Status = &v
}

// GetSuccessTime returns the SuccessTime field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetSuccessTime() string {
	if o == nil || o.SuccessTime == nil {
		var ret string
		return ret
	}
	return *o.SuccessTime
}

// GetSuccessTimeOk returns a tuple with the SuccessTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetSuccessTimeOk() (*string, bool) {
	if o == nil || o.SuccessTime == nil {
		return nil, false
	}
	return o.SuccessTime, true
}

// HasSuccessTime returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasSuccessTime() bool {
	if o != nil && o.SuccessTime != nil {
		return true
	}

	return false
}

// SetSuccessTime gets a reference to the given string and assigns it to the SuccessTime field.
func (o *ModelsWechatRefundDetail) SetSuccessTime(v string) {
	o.SuccessTime = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetTransactionId() string {
	if o == nil || o.TransactionId == nil {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetTransactionIdOk() (*string, bool) {
	if o == nil || o.TransactionId == nil {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasTransactionId() bool {
	if o != nil && o.TransactionId != nil {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *ModelsWechatRefundDetail) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ModelsWechatRefundDetail) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUserReceivedAccount returns the UserReceivedAccount field value if set, zero value otherwise.
func (o *ModelsWechatRefundDetail) GetUserReceivedAccount() string {
	if o == nil || o.UserReceivedAccount == nil {
		var ret string
		return ret
	}
	return *o.UserReceivedAccount
}

// GetUserReceivedAccountOk returns a tuple with the UserReceivedAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsWechatRefundDetail) GetUserReceivedAccountOk() (*string, bool) {
	if o == nil || o.UserReceivedAccount == nil {
		return nil, false
	}
	return o.UserReceivedAccount, true
}

// HasUserReceivedAccount returns a boolean if a field has been set.
func (o *ModelsWechatRefundDetail) HasUserReceivedAccount() bool {
	if o != nil && o.UserReceivedAccount != nil {
		return true
	}

	return false
}

// SetUserReceivedAccount gets a reference to the given string and assigns it to the UserReceivedAccount field.
func (o *ModelsWechatRefundDetail) SetUserReceivedAccount(v string) {
	o.UserReceivedAccount = &v
}

func (o ModelsWechatRefundDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Channel != nil {
		toSerialize["channel"] = o.Channel
	}
	if o.CreateTime != nil {
		toSerialize["create_time"] = o.CreateTime
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.DeletedAt != nil {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if o.FundsAccount != nil {
		toSerialize["funds_account"] = o.FundsAccount
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.OutRefundNo != nil {
		toSerialize["out_refund_no"] = o.OutRefundNo
	}
	if o.OutTradeNo != nil {
		toSerialize["out_trade_no"] = o.OutTradeNo
	}
	if o.RefundId != nil {
		toSerialize["refund_id"] = o.RefundId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.SuccessTime != nil {
		toSerialize["success_time"] = o.SuccessTime
	}
	if o.TransactionId != nil {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.UserReceivedAccount != nil {
		toSerialize["user_received_account"] = o.UserReceivedAccount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ModelsWechatRefundDetail) UnmarshalJSON(bytes []byte) (err error) {
	varModelsWechatRefundDetail := _ModelsWechatRefundDetail{}

	if err = json.Unmarshal(bytes, &varModelsWechatRefundDetail); err == nil {
		*o = ModelsWechatRefundDetail(varModelsWechatRefundDetail)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "channel")
		delete(additionalProperties, "create_time")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "deleted_at")
		delete(additionalProperties, "funds_account")
		delete(additionalProperties, "id")
		delete(additionalProperties, "out_refund_no")
		delete(additionalProperties, "out_trade_no")
		delete(additionalProperties, "refund_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "success_time")
		delete(additionalProperties, "transaction_id")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "user_received_account")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelsWechatRefundDetail struct {
	value *ModelsWechatRefundDetail
	isSet bool
}

func (v NullableModelsWechatRefundDetail) Get() *ModelsWechatRefundDetail {
	return v.value
}

func (v *NullableModelsWechatRefundDetail) Set(val *ModelsWechatRefundDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsWechatRefundDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsWechatRefundDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsWechatRefundDetail(val *ModelsWechatRefundDetail) *NullableModelsWechatRefundDetail {
	return &NullableModelsWechatRefundDetail{value: val, isSet: true}
}

func (v NullableModelsWechatRefundDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsWechatRefundDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


