/*
Rainbow-API

Conflux-Pay API documentation

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluxpay

import (
	"encoding/json"
)

// ServicesMakeOrderReq struct for ServicesMakeOrderReq
type ServicesMakeOrderReq struct {
	Amount int32 `json:"amount"`
	Description string `json:"description"`
	NotifyUrl *string `json:"notify_url,omitempty"`
	TimeExpire int32 `json:"time_expire"`
	TradeType string `json:"trade_type"`
	AdditionalProperties map[string]interface{}
}

type _ServicesMakeOrderReq ServicesMakeOrderReq

// NewServicesMakeOrderReq instantiates a new ServicesMakeOrderReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesMakeOrderReq(amount int32, description string, timeExpire int32, tradeType string) *ServicesMakeOrderReq {
	this := ServicesMakeOrderReq{}
	this.Amount = amount
	this.Description = description
	this.TimeExpire = timeExpire
	this.TradeType = tradeType
	return &this
}

// NewServicesMakeOrderReqWithDefaults instantiates a new ServicesMakeOrderReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesMakeOrderReqWithDefaults() *ServicesMakeOrderReq {
	this := ServicesMakeOrderReq{}
	return &this
}

// GetAmount returns the Amount field value
func (o *ServicesMakeOrderReq) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ServicesMakeOrderReq) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ServicesMakeOrderReq) SetAmount(v int32) {
	o.Amount = v
}

// GetDescription returns the Description field value
func (o *ServicesMakeOrderReq) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ServicesMakeOrderReq) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ServicesMakeOrderReq) SetDescription(v string) {
	o.Description = v
}

// GetNotifyUrl returns the NotifyUrl field value if set, zero value otherwise.
func (o *ServicesMakeOrderReq) GetNotifyUrl() string {
	if o == nil || o.NotifyUrl == nil {
		var ret string
		return ret
	}
	return *o.NotifyUrl
}

// GetNotifyUrlOk returns a tuple with the NotifyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeOrderReq) GetNotifyUrlOk() (*string, bool) {
	if o == nil || o.NotifyUrl == nil {
		return nil, false
	}
	return o.NotifyUrl, true
}

// HasNotifyUrl returns a boolean if a field has been set.
func (o *ServicesMakeOrderReq) HasNotifyUrl() bool {
	if o != nil && o.NotifyUrl != nil {
		return true
	}

	return false
}

// SetNotifyUrl gets a reference to the given string and assigns it to the NotifyUrl field.
func (o *ServicesMakeOrderReq) SetNotifyUrl(v string) {
	o.NotifyUrl = &v
}

// GetTimeExpire returns the TimeExpire field value
func (o *ServicesMakeOrderReq) GetTimeExpire() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TimeExpire
}

// GetTimeExpireOk returns a tuple with the TimeExpire field value
// and a boolean to check if the value has been set.
func (o *ServicesMakeOrderReq) GetTimeExpireOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeExpire, true
}

// SetTimeExpire sets field value
func (o *ServicesMakeOrderReq) SetTimeExpire(v int32) {
	o.TimeExpire = v
}

// GetTradeType returns the TradeType field value
func (o *ServicesMakeOrderReq) GetTradeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradeType
}

// GetTradeTypeOk returns a tuple with the TradeType field value
// and a boolean to check if the value has been set.
func (o *ServicesMakeOrderReq) GetTradeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradeType, true
}

// SetTradeType sets field value
func (o *ServicesMakeOrderReq) SetTradeType(v string) {
	o.TradeType = v
}

func (o ServicesMakeOrderReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if o.NotifyUrl != nil {
		toSerialize["notify_url"] = o.NotifyUrl
	}
	if true {
		toSerialize["time_expire"] = o.TimeExpire
	}
	if true {
		toSerialize["trade_type"] = o.TradeType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ServicesMakeOrderReq) UnmarshalJSON(bytes []byte) (err error) {
	varServicesMakeOrderReq := _ServicesMakeOrderReq{}

	if err = json.Unmarshal(bytes, &varServicesMakeOrderReq); err == nil {
		*o = ServicesMakeOrderReq(varServicesMakeOrderReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "description")
		delete(additionalProperties, "notify_url")
		delete(additionalProperties, "time_expire")
		delete(additionalProperties, "trade_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesMakeOrderReq struct {
	value *ServicesMakeOrderReq
	isSet bool
}

func (v NullableServicesMakeOrderReq) Get() *ServicesMakeOrderReq {
	return v.value
}

func (v *NullableServicesMakeOrderReq) Set(val *ServicesMakeOrderReq) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesMakeOrderReq) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesMakeOrderReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesMakeOrderReq(val *ServicesMakeOrderReq) *NullableServicesMakeOrderReq {
	return &NullableServicesMakeOrderReq{value: val, isSet: true}
}

func (v NullableServicesMakeOrderReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesMakeOrderReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


