/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confluxpay

import (
	"encoding/json"
)

// ServicesMakeWechatOrderReq struct for ServicesMakeWechatOrderReq
type ServicesMakeWechatOrderReq struct {
	Amount *int32 `json:"amount,omitempty"`
	Description *string `json:"description,omitempty"`
	TimeExpire *int32 `json:"time_expire,omitempty"`
	TradeType *int32 `json:"trade_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServicesMakeWechatOrderReq ServicesMakeWechatOrderReq

// NewServicesMakeWechatOrderReq instantiates a new ServicesMakeWechatOrderReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesMakeWechatOrderReq() *ServicesMakeWechatOrderReq {
	this := ServicesMakeWechatOrderReq{}
	return &this
}

// NewServicesMakeWechatOrderReqWithDefaults instantiates a new ServicesMakeWechatOrderReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesMakeWechatOrderReqWithDefaults() *ServicesMakeWechatOrderReq {
	this := ServicesMakeWechatOrderReq{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ServicesMakeWechatOrderReq) GetAmount() int32 {
	if o == nil || o.Amount == nil {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeWechatOrderReq) GetAmountOk() (*int32, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ServicesMakeWechatOrderReq) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ServicesMakeWechatOrderReq) SetAmount(v int32) {
	o.Amount = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServicesMakeWechatOrderReq) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeWechatOrderReq) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServicesMakeWechatOrderReq) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServicesMakeWechatOrderReq) SetDescription(v string) {
	o.Description = &v
}

// GetTimeExpire returns the TimeExpire field value if set, zero value otherwise.
func (o *ServicesMakeWechatOrderReq) GetTimeExpire() int32 {
	if o == nil || o.TimeExpire == nil {
		var ret int32
		return ret
	}
	return *o.TimeExpire
}

// GetTimeExpireOk returns a tuple with the TimeExpire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeWechatOrderReq) GetTimeExpireOk() (*int32, bool) {
	if o == nil || o.TimeExpire == nil {
		return nil, false
	}
	return o.TimeExpire, true
}

// HasTimeExpire returns a boolean if a field has been set.
func (o *ServicesMakeWechatOrderReq) HasTimeExpire() bool {
	if o != nil && o.TimeExpire != nil {
		return true
	}

	return false
}

// SetTimeExpire gets a reference to the given int32 and assigns it to the TimeExpire field.
func (o *ServicesMakeWechatOrderReq) SetTimeExpire(v int32) {
	o.TimeExpire = &v
}

// GetTradeType returns the TradeType field value if set, zero value otherwise.
func (o *ServicesMakeWechatOrderReq) GetTradeType() int32 {
	if o == nil || o.TradeType == nil {
		var ret int32
		return ret
	}
	return *o.TradeType
}

// GetTradeTypeOk returns a tuple with the TradeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesMakeWechatOrderReq) GetTradeTypeOk() (*int32, bool) {
	if o == nil || o.TradeType == nil {
		return nil, false
	}
	return o.TradeType, true
}

// HasTradeType returns a boolean if a field has been set.
func (o *ServicesMakeWechatOrderReq) HasTradeType() bool {
	if o != nil && o.TradeType != nil {
		return true
	}

	return false
}

// SetTradeType gets a reference to the given int32 and assigns it to the TradeType field.
func (o *ServicesMakeWechatOrderReq) SetTradeType(v int32) {
	o.TradeType = &v
}

func (o ServicesMakeWechatOrderReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.TimeExpire != nil {
		toSerialize["time_expire"] = o.TimeExpire
	}
	if o.TradeType != nil {
		toSerialize["trade_type"] = o.TradeType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ServicesMakeWechatOrderReq) UnmarshalJSON(bytes []byte) (err error) {
	varServicesMakeWechatOrderReq := _ServicesMakeWechatOrderReq{}

	if err = json.Unmarshal(bytes, &varServicesMakeWechatOrderReq); err == nil {
		*o = ServicesMakeWechatOrderReq(varServicesMakeWechatOrderReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "description")
		delete(additionalProperties, "time_expire")
		delete(additionalProperties, "trade_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesMakeWechatOrderReq struct {
	value *ServicesMakeWechatOrderReq
	isSet bool
}

func (v NullableServicesMakeWechatOrderReq) Get() *ServicesMakeWechatOrderReq {
	return v.value
}

func (v *NullableServicesMakeWechatOrderReq) Set(val *ServicesMakeWechatOrderReq) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesMakeWechatOrderReq) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesMakeWechatOrderReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesMakeWechatOrderReq(val *ServicesMakeWechatOrderReq) *NullableServicesMakeWechatOrderReq {
	return &NullableServicesMakeWechatOrderReq{value: val, isSet: true}
}

func (v NullableServicesMakeWechatOrderReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesMakeWechatOrderReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


